#!/bin/bash

#get the current owner of the file hello
 current_owner=$(stat -c %U hello)

#check if the file is owned by 'guillaume'
 if [ "$current_owner" = 'guillaume' ]; then
         echo "File is currently owned by guillaume. Proceeding to change owner to vincent. "

#change the owner to vincent
         sudo chown vincent hello
         echo "file ownership changed to vincent "
 else
         echo "No change: file is not owned by guillaume (current owner is $current_owner "
 fi
